### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by sauliusgrigaitis** [herumi/bls-eth-rust#4]
Thanks a lot for working on a such performant BLS library!

I'm trying to build `bls-eth-rust` via Github Workflows on `windows-latest` with target `x86_64-pc-windows-msvc`, however it has an issue https://github.com/SifraiHQ/bls-eth-rust/runs/2122130388 .

**Comment by herumi** [comment]
I've removed `stdc++` at https://github.com/herumi/bls-eth-rust/commit/79a8271e1263879e25d0679afd7d0ed20105a10d .

**Comment by sauliusgrigaitis** [comment]
Thank you. However, it still doesn't work. The problem is with `bls-eth-go-binary`, it is created with MinGW's g++ so it can not be linked with MSVC. You can see how to test with `x86_64-pc-windows-msvc` on Github Workflows here https://github.com/SifraiHQ/bls-eth-rust/commit/b499b35e785a27f9f5bb84f5a52f711d19ae4867 .

The solution would be to either build `bls-eth-go-binary` on native Windows machine or build with Github Workflows on `windows-latest` target with MSVC.

**Comment by herumi** [comment]
The static library in `bls-eth-go-binary` is for Golang and it is compiled by mingw64 and so it is for `x86_64-pc-windows-gnu`.
To get a static library compiled by MSVC, then run the following commands:

```
mkdir work
git clone git@github.com:herumi/mcl
git clone git@github.com:herumi/bls
git clone git@github.com:herumi/bls-eth-rust
cd bls
mklib eth
cd ../bls-eth-rust
set RUSTLFAGS=-L../bls/lib
cargo test --target=x86_64-pc-windows-msvc
```

On my env(Visual Studio 16.9.2 and cargo 1.50.0 (f04e7fab7 2021-02-04)), 
```
>bls-eth-rust>cargo test --target=x86_64-pc-windows-msvc
   Compiling bls_eth_rust v0.0.2 (C:\prog\bls-eth-rust)
    Finished test [unoptimized + debuginfo] target(s) in 0.61s
     Running target\x86_64-pc-windows-msvc\debug\deps\bls_eth_rust-8bcb7d80d8e743bf.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target\x86_64-pc-windows-msvc\debug\deps\test-b376fc27c3a8a06f.exe

running 11 tests
test test_are_all_msg_different ... ok
test test_from_serialized_publickey ... ok
test test_eth_draft07 ... ok
test test_eth_aggregate ... ok
test test_eth_aggregate_verify_no_check1 ... ok
test test_from_serialized_signature ... ok
test test_sign_serialize ... ok
test test_fast_aggregate_verify ... ok
test test_eth_sign ... ok
test test_eth_aggregate_verify_no_check2 ... ok
test test_multi_verify ... ok

test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.76s

   Doc-tests bls_eth_rust

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
